name: movie_ticket
description: "A movie ticket application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  flutter_native_splash: ^2.4.4
  iconly: ^1.0.1
  intl: ^0.20.2
  dots_indicator: ^4.0.1
  barcode_widget: ^2.0.4
  flutter_riverpod: ^2.6.1
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.4
  http: ^1.3.0
  readmore: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
